version: 2
archives:
- id: archive
  name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
  - make tfgen
builds:
- binary: pulumi-resource-crowdstrike
  dir: provider
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ignore: []
  ldflags:
  - -X github.com/crowdstrike/pulumi-crowdstrike/provider/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-crowdstrike/
release:
  disable: false
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT" 